apiVersion: v1
kind: Service
metadata:
  name: kube-rsync-machine-controller-manager
  labels:
    app.kubernetes.io/name: kube-rsync-machine
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/part-of: kube-rsync-machine
    control-plane: controller-manager
spec:
  selector:
    app.kubernetes.io/name: kube-rsync-machine
    app.kubernetes.io/component: controller-manager
    control-plane: controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: live-api
      port: 8082
      targetPort: live-api
    - name: control-grpc
      port: 8083
      targetPort: control-grpc
