apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-rsync-machine-leader-election-role
  labels:
    app.kubernetes.io/name: kube-rsync-machine
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/part-of: kube-rsync-machine
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
