apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rsync-machine-controller-manager
  labels:
    app.kubernetes.io/name: kube-rsync-machine
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/part-of: kube-rsync-machine
